### PR TITLE
Use a Markdown version of the GPLv3

### PR DESCRIPTION
**Pull request by Calinou**
Obtained from https://www.gnu.org/licenses/gpl-3.0.md, which is an official source.

### CODE REVIEW

**Comment by Calinou** [comment]
Bump :slightly_smiling_face:

**Comment by Calinou** [comment]
Bump (again) :slightly_smiling_face: 

cc @Lurkki14

**Comment by justjosias** [comment]
@Calinou Is this really necessary though? Most projects that I have run across use the normal LICENSE text file without any extra formatting. It is still very readable.

**Comment by Calinou** [comment]
@justjosias It's not necessary, but I guess it's nice to have.

**Pull request closed without merging**
